version: '3.2'

# example to run the devel image via docker-compose

services:
  hello_world_devel:
    image: developmentimage/docker_image_development:devel
    command: "hello_world"
    #ports:
    #  - "7890:7890"
    #expose:
    #  - "7890"
    volumes:
    # mount devel folders
    - ./startscripts:/opt/startscripts
    - ./workspace:/opt/workspace
    - ./home:/home/dockeruser

